[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pyspextool"
version = "0.0.1"
# dependencies = [
#    "requests",
#    'importlib-metadata; python_version<"3.8"',
#]

[tool.pytest.ini_options]
pythonpath = [
  "."
]