[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pyspextool"
version = "0.0.1"
dependencies = [
    "astropy",
    "scipy",
    "matplotlib",
    "numpy",
]
[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
"pyspextool.instrument_data" = ["*.dat","*.fits"]